# Generated by Django 4.2.13 on 2026-01-22 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_tasks', to='user_profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Single Tasks',
                'ordering': ['-date', 'user_profile', 'task_name'],
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
