# Generated by Django 4.2.13 on 2026-02-03 01:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_group_name', models.CharField(max_length=255)),
                ('interval_in_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('task_group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_task_groups', to='user_profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Interval Task Groups',
                'ordering': ['task_group_owner__user__username', 'task_group_name'],
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IntervalTaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_task_name', models.CharField(max_length=255)),
                ('interval_task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_tasks', to='interval_task_group.intervaltaskgroup')),
            ],
            options={
                'verbose_name_plural': 'Interval Task Schedulers',
                'ordering': ['interval_task_group', 'interval_task_name'],
            },
        ),
        migrations.CreateModel(
            name='IntervalTaskGroupAppliedQuarterly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2035)])),
                ('interval_task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_applications', to='interval_task_group.intervaltaskgroup')),
            ],
            options={
                'verbose_name_plural': 'Interval Task Groups Applied Quarterly',
                'ordering': ['-year', '-quarter', 'interval_task_group__task_group_owner__user__username', 'interval_task_group__task_group_name'],
                'unique_together': {('quarter', 'year', 'interval_task_group')},
            },
        ),
    ]
