# Generated by Django 4.2.13 on 2026-01-24 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_task_name', models.CharField(max_length=255)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_task_schedulers', to='user_profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Weekly Task Schedulers',
                'ordering': ['user_profile__user__username', 'day_of_week', 'weekly_task_name'],
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTaskAppliedQuarterly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2035)])),
                ('weekly_task_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_applications', to='weekly_task.weeklytaskscheduler')),
            ],
            options={
                'verbose_name_plural': 'Weekly Tasks Applied Quarterly',
                'ordering': ['-year', '-quarter', 'weekly_task_scheduler__user_profile__user__username', 'weekly_task_scheduler__weekly_task_name'],
                'unique_together': {('quarter', 'year', 'weekly_task_scheduler')},
            },
        ),
    ]
