# Generated by Django 4.2.13 on 2026-01-31 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_task_name', models.CharField(max_length=255)),
                ('day_of_month', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_task_schedulers', to='user_profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Monthly Task Schedulers',
                'ordering': ['user_profile__user__username', 'day_of_month', 'monthly_task_name'],
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTaskAppliedQuarterly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2035)])),
                ('monthly_task_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_applications', to='monthly_task.monthlytaskscheduler')),
            ],
            options={
                'verbose_name_plural': 'Monthly Tasks Applied Quarterly',
                'ordering': ['-year', '-quarter', 'monthly_task_scheduler__user_profile__user__username', 'monthly_task_scheduler__monthly_task_name'],
                'unique_together': {('quarter', 'year', 'monthly_task_scheduler')},
            },
        ),
    ]
